// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgjlxycxbojgogydzbwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnamx4eWN4Ym9qZ29neWR6YndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzY5MzMsImV4cCI6MjA2MTUxMjkzM30.k8Imnrmey2mabbtknbmeXC4duZ-LkOlaMmw94cGailM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);